services:
  - type: web
    name: agro-nexus-backend
    env: python
    region: singapore  # Choose the region closest to your users
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GEE_SERVICE_ACCOUNT
        sync: false  # Add this in Render dashboard
    healthCheckPath: /test
    autoDeploy: true 